my_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  #my_robot_x_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: my_robot_x
  #  pid: {p: 100.0, i: 0.01, d: 10.0}

  my_robot_y_position_controller:
    type: effort_controllers/JointPositionController
    joint: my_robot_y
    pid: {p: 100.0, i: 0.01, d: 10.0}

  #my_robot_entity_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: entity
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
