<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <xacro:property name="length" value="1" />
  <xacro:property name="width" value="1" />
  <xacro:property name="height" value="0.5" />

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <origin rpy="0.0 0 0" xyz="0 0 0"/>
      <mass value="${mass}" />
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2" />
    </inertial>
  </xacro:macro>

  <link name="world"/>

  <link name="my_robot_xpart">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <gazebo reference="my_robot_xpart">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
    <material> Gazebo/GreyTransparent</material>
  </gazebo>

  <joint name="my_robot_x" type="prismatic">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="my_robot_xpart"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0" friction="0"/>
    <limit effort="10000" lower="-50.0" upper="50.0" velocity="1"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="my_robot_x">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="my_robot_ypart">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <gazebo reference="my_robot_ypart">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
    <material> Gazebo/Blue</material>
  </gazebo>

  <joint name="my_robot_y" type="prismatic">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="my_robot_xpart"/>
    <child link="my_robot_ypart"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0" friction="0"/>
    <limit effort="10000" lower="-50.0" upper="50.0" velocity="1"/>
  </joint>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="my_robot_y">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
<!--
  <joint name="entity" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="my_robot_xpart"/>
    <child link="my_robot_ypart"/>
  </joint>-->


  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/my_robot</robotNamespace>
    </plugin>
  </gazebo>

</robot>
