<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <xacro:property name="length" value="1" />
  <xacro:property name="width" value="1" />
  <xacro:property name="height" value="0.5" />
  <xacro:property name="length_wheel_disc" value="0.01" />
  <xacro:property name="radius_wheel_disc" value="0.15" />
  <xacro:property name="length_wheel" value="0.11" />
  <xacro:property name="radius_wheel" value="0.12" />
  <xacro:property name="wheel_offset" value="0.505" />


  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <origin rpy="0.0 0 0" xyz="0 0 0"/>
      <mass value="${mass}" />
      <!--<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="0.0" />-->
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" />
    </inertial>
  </xacro:macro>
<!--
  <link name="my_robot_xpart">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <gazebo reference="my_robot_xpart">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
    <material> Gazebo/GreyTransparent</material>
  </gazebo>

  <joint name="my_robot_x" type="prismatic">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="my_robot_xpart"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0" friction="0"/>
    <limit effort="10000" lower="-50.0" upper="50.0" velocity="1"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="my_robot_x">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
-->

<link name="base_footprint">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0 0 0"/>
    </geometry>
  </visual>
  <collision>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0 0 0"/>
    </geometry>
  </collision>
  <xacro:default_inertial mass="0.1"/>
</link>


  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height/2}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

  <link name="wheel_1">
    <visual>
      <geometry>
        <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <visual>
      <geometry>
        <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.055"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <collision>
      <geometry>
        <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.055"/>
    </collision>

    <xacro:default_inertial mass="3"/>
</link>



<link name="wheel_2">
  <visual>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 -0.055"/>
  </collision>

  <visual>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 -0.055"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </collision>

  <xacro:default_inertial mass="3"/>
</link>


<link name="wheel_3">
  <visual>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0.055"/>
  </collision>

  <visual>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0.055"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </collision>

  <xacro:default_inertial mass="3"/>
</link>


<link name="wheel_4">
  <visual>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 -0.055"/>
  </collision>

  <visual>
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 -0.055"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${length_wheel_disc}" radius="${radius_wheel_disc}"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </collision>

  <xacro:default_inertial mass="3"/>
</link>

<link name="imu_link">
  <visual>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <material name="black">
          <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>
  <xacro:default_inertial mass="0.1"/>
</link>

<link name="laserscan_link">
  <visual>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>
  <xacro:default_inertial mass="0.1"/>
</link>

<link name="camera_link">
  <visual>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>
  <xacro:default_inertial mass="0.1"/>
</link>


  <joint name="my_robot_base" type="prismatic">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1" friction="1"/>
    <limit effort="10000" lower="-50.0" upper="600.0" velocity="0.1"/>
  </joint>


  <joint name="base_to_wheel1" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_1"/>
    <origin rpy="0 1.5707 0" xyz="${wheel_offset} 0.4 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_wheel2" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_2"/>
    <origin rpy="0 1.5707 0" xyz="${-wheel_offset} 0.4 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_wheel3" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_3"/>
    <origin rpy="0 1.5707 0" xyz="${wheel_offset} -0.4 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_wheel4" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_4"/>
    <origin rpy="0 1.5707 0" xyz="${-wheel_offset} -0.4 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_imu" type="continuous">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.175"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_laserscan" type="continuous">
    <parent link="base_link"/>
    <child link="laserscan_link"/>
    <origin rpy="0.0 0.0 ${pi}" xyz="0.0 0.2 0.175"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="base_to_camera" type="continuous">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin rpy="0.0 0.0 ${pi/2}" xyz="0.2 0.2 0.175"/>
    <axis xyz="0 0 1" />
  </joint>


  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="my_robot_base">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="transmission_wheel_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_wheel1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_wheel_1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<transmission name="transmission_wheel_2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="base_to_wheel2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor_wheel_2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<!--
  <joint name="entity" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="my_robot_xpart"/>
    <child link="my_robot_ypart"/>
  </joint>-->
<gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <gravity>1</gravity>
</gazebo>

<gazebo reference="wheel_1">
  <mu1 value="200.0"/>
  <mu2 value="100.0"/>
  <kp value="10000000.0" />
  <kd value="1.0" />
  <material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel_2">
  <mu1 value="200.0"/>
  <mu2 value="100.0"/>
  <kp value="10000000.0" />
  <kd value="1.0" />
  <material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel_3">
  <mu1 value="200.0"/>
  <mu2 value="100.0"/>
  <kp value="10000000.0" />
  <kd value="1.0" />
  <material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel_4">
  <mu1 value="200.0"/>
  <mu2 value="100.0"/>
  <kp value="10000000.0" />
  <kd value="1.0" />
  <material>Gazebo/Yellow</material></gazebo>
  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/my_robot</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Gazebo plugin for IMU-->
  <gazebo reference="imu_link">
    <material>Gazebo/Black</material>
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

    <!-- Gazebo plugin for laser scan sensor-->
  <gazebo reference="laserscan_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Orange</material>
  </gazebo>
<gazebo reference="laserscan_link">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/rrbot/laser/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- camera -->
   <gazebo reference="camera_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>rrbot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link_optical</frameName>
        <!-- setting hackBaseline to anything but 0.0 will cause a misalignment
            between the gazebo sensor image and the frame it is supposed to
            be attached to -->
        <hackBaseline>0.0</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0.0</Cx>
        <Cy>0.0</Cy>
        <focalLength>0.0</focalLength>
      </plugin>
    </sensor>
  </gazebo>

</robot>
